//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMineServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveGame
    {
        public int Serial { get; set; }
        public string Player1Name { get; set; }
        public string Player2Name { get; set; }
        public System.DateTime GameStarted { get; set; }
    }
}
